In [1]:
import glob
import pandas as pd

import re

from tqdm import tqdm
tqdm.pandas()

# pd.options.display.width = 1000
# pd.set_option('display.expand_frame_repr', False)
# pd.set_option('max_colwidth', 1000)

In [2]:
df_list = []
chunks = glob.glob("collecting/data/pure_rwt/" + "*.csv")
assert len(chunks) > 0

for filename in chunks:
    df = pd.read_csv(
        filepath_or_buffer=filename,
        sep="⇧",
        engine="python",
        quotechar='"',
        on_bad_lines="warn",
        nrows=None
    )
    df_list.append(df)
df = pd.concat(df_list, axis=0)
df.reset_index(inplace=True, drop=True)
df

Skipping line 295421: field larger than field limit (131072)
Skipping line 5451: Expected 4 fields in line 5451, saw 5
Skipping line 49580: Expected 4 fields in line 49580, saw 5
Skipping line 49974: Expected 4 fields in line 49974, saw 5
Skipping line 58587: Expected 4 fields in line 58587, saw 18
Skipping line 58588: Expected 4 fields in line 58588, saw 6
Skipping line 151972: Expected 4 fields in line 151972, saw 5
Skipping line 182891: Expected 4 fields in line 182891, saw 5
Skipping line 207672: Expected 4 fields in line 207672, saw 5
Skipping line 218885: Expected 4 fields in line 218885, saw 5
Skipping line 224913: Expected 4 fields in line 224913, saw 7
Skipping line 225919: Expected 4 fields in line 225919, saw 5
Skipping line 243369: Expected 4 fields in line 243369, saw 5
Skipping line 253426: Expected 4 fields in line 253426, saw 5
Skipping line 263318: Expected 4 fields in line 263318, saw 5
Skipping line 283644: Expected 4 fields in line 283644, saw 5
Skipping line 289180: Expected 4 fields in line 289180, saw 5
Skipping line 393114: Expected 4 fields in line 393114, saw 5
Skipping line 420230: Expected 4 fields in line 420230, saw 6
Skipping line 433110: Expected 4 fields in line 433110, saw 5
Skipping line 500922: Expected 4 fields in line 500922, saw 5
Skipping line 501870: Expected 4 fields in line 501870, saw 5
Skipping line 505071: Expected 4 fields in line 505071, saw 5
Skipping line 529445: Expected 4 fields in line 529445, saw 5
Skipping line 529621: Expected 4 fields in line 529621, saw 5
Skipping line 536380: Expected 4 fields in line 536380, saw 18
Skipping line 536381: Expected 4 fields in line 536381, saw 6
Skipping line 543439: Expected 4 fields in line 543439, saw 5
Skipping line 597359: Expected 4 fields in line 597359, saw 5
Skipping line 598421: Expected 4 fields in line 598421, saw 5
Skipping line 199894: field larger than field limit (131072)
Skipping line 220236: field larger than field limit (131072)
Skipping line 7934: Expected 4 fields in line 7934, saw 5
Skipping line 21853: Expected 4 fields in line 21853, saw 5
Skipping line 41688: Expected 4 fields in line 41688, saw 5
Skipping line 48120: Expected 4 fields in line 48120, saw 5
Skipping line 57112: Expected 4 fields in line 57112, saw 5
Skipping line 88828: Expected 4 fields in line 88828, saw 5
Skipping line 114814: Expected 4 fields in line 114814, saw 5
Skipping line 117881: Expected 4 fields in line 117881, saw 5
Skipping line 215792: Expected 4 fields in line 215792, saw 5
Skipping line 218025: Expected 4 fields in line 218025, saw 5
Skipping line 227571: Expected 4 fields in line 227571, saw 5
Skipping line 228826: Expected 4 fields in line 228826, saw 5
Skipping line 231926: Expected 4 fields in line 231926, saw 5
Skipping line 241837: Expected 4 fields in line 241837, saw 5
Skipping line 243765: Expected 4 fields in line 243765, saw 5
Skipping line 250834: Expected 4 fields in line 250834, saw 5
Skipping line 272187: Expected 4 fields in line 272187, saw 5
Skipping line 278634: Expected 4 fields in line 278634, saw 5
Skipping line 325959: Expected 4 fields in line 325959, saw 5
Skipping line 339662: Expected 4 fields in line 339662, saw 6
Skipping line 349892: Expected 4 fields in line 349892, saw 5
Skipping line 356749: Expected 4 fields in line 356749, saw 5
Skipping line 361553: Expected 4 fields in line 361553, saw 5
Skipping line 383925: Expected 4 fields in line 383925, saw 5
Skipping line 405829: Expected 4 fields in line 405829, saw 6
Skipping line 412096: Expected 4 fields in line 412096, saw 5
Skipping line 421308: Expected 4 fields in line 421308, saw 5
Skipping line 457707: Expected 4 fields in line 457707, saw 5
Skipping line 464370: Expected 4 fields in line 464370, saw 5
Skipping line 466940: Expected 4 fields in line 466940, saw 5
Skipping line 474708: Expected 4 fields in line 474708, saw 5
Skipping line 478173: Expected 4 fields in line 478173, saw 5
Skipping line 492419: Expected 4 fields in line 492419, saw 5
Skipping line 531013: Expected 4 fields in line 531013, saw 6
Skipping line 534309: Expected 4 fields in line 534309, saw 5
Skipping line 535523: Expected 4 fields in line 535523, saw 6
Skipping line 537548: Expected 4 fields in line 537548, saw 5
Skipping line 549501: Expected 4 fields in line 549501, saw 5
Skipping line 574438: Expected 4 fields in line 574438, saw 5
Skipping line 579170: Expected 4 fields in line 579170, saw 5
Skipping line 597913: Expected 4 fields in line 597913, saw 5
Skipping line 1275: Expected 4 fields in line 1275, saw 5
Skipping line 24853: Expected 4 fields in line 24853, saw 5
Skipping line 62890: Expected 4 fields in line 62890, saw 5
Skipping line 70990: Expected 4 fields in line 70990, saw 5
Skipping line 77657: Expected 4 fields in line 77657, saw 5
Skipping line 77936: Expected 4 fields in line 77936, saw 5
Skipping line 78362: Expected 4 fields in line 78362, saw 5
Skipping line 86974: Expected 4 fields in line 86974, saw 5
Skipping line 108524: Expected 4 fields in line 108524, saw 5
Skipping line 134304: Expected 4 fields in line 134304, saw 5
Skipping line 170745: Expected 4 fields in line 170745, saw 5
Skipping line 171015: Expected 4 fields in line 171015, saw 5
Skipping line 191412: Expected 4 fields in line 191412, saw 6
Skipping line 196791: Expected 4 fields in line 196791, saw 5
Skipping line 205910: Expected 4 fields in line 205910, saw 5
Skipping line 206316: Expected 4 fields in line 206316, saw 5
Skipping line 225376: Expected 4 fields in line 225376, saw 5
Skipping line 230024: Expected 4 fields in line 230024, saw 5
Skipping line 239672: Expected 4 fields in line 239672, saw 5
Skipping line 253112: Expected 4 fields in line 253112, saw 6
Skipping line 265428: Expected 4 fields in line 265428, saw 5
Skipping line 271291: Expected 4 fields in line 271291, saw 18
Skipping line 271292: Expected 4 fields in line 271292, saw 6
Skipping line 310912: Expected 4 fields in line 310912, saw 5
Skipping line 322974: Expected 4 fields in line 322974, saw 5
Skipping line 332354: Expected 4 fields in line 332354, saw 5
Skipping line 344572: Expected 4 fields in line 344572, saw 5
Skipping line 345881: Expected 4 fields in line 345881, saw 5
Skipping line 348499: Expected 4 fields in line 348499, saw 5
Skipping line 351676: Expected 4 fields in line 351676, saw 5
Skipping line 359989: Expected 4 fields in line 359989, saw 5
Skipping line 363273: Expected 4 fields in line 363273, saw 5
Skipping line 383227: Expected 4 fields in line 383227, saw 5
Skipping line 385576: Expected 4 fields in line 385576, saw 5
Skipping line 389462: Expected 4 fields in line 389462, saw 5
Skipping line 401693: Expected 4 fields in line 401693, saw 5
Skipping line 416594: Expected 4 fields in line 416594, saw 5
Skipping line 424360: Expected 4 fields in line 424360, saw 5
Skipping line 426616: Expected 4 fields in line 426616, saw 5
Skipping line 443270: Expected 4 fields in line 443270, saw 5
Skipping line 444315: Expected 4 fields in line 444315, saw 6
Skipping line 445116: Expected 4 fields in line 445116, saw 5
Skipping line 453471: Expected 4 fields in line 453471, saw 5
Skipping line 458767: Expected 4 fields in line 458767, saw 5
Skipping line 475728: Expected 4 fields in line 475728, saw 5
Skipping line 492197: Expected 4 fields in line 492197, saw 5
Skipping line 504642: Expected 4 fields in line 504642, saw 5
Skipping line 512279: Expected 4 fields in line 512279, saw 5
Skipping line 532501: Expected 4 fields in line 532501, saw 5
Skipping line 539404: Expected 4 fields in line 539404, saw 5
Skipping line 541995: Expected 4 fields in line 541995, saw 5
Skipping line 548035: Expected 4 fields in line 548035, saw 5
Skipping line 556409: Expected 4 fields in line 556409, saw 5
Skipping line 566556: Expected 4 fields in line 566556, saw 5
Skipping line 573350: Expected 4 fields in line 573350, saw 5
Skipping line 580320: Expected 4 fields in line 580320, saw 5
Skipping line 598378: Expected 4 fields in line 598378, saw 6
Skipping line 614407: Expected 4 fields in line 614407, saw 5
Skipping line 221453: field larger than field limit (131072)
Skipping line 382761: field larger than field limit (131072)
Skipping line 1382: Expected 4 fields in line 1382, saw 5
Skipping line 4433: Expected 4 fields in line 4433, saw 5
Skipping line 10633: Expected 4 fields in line 10633, saw 5
Skipping line 14985: Expected 4 fields in line 14985, saw 5
Skipping line 29861: Expected 4 fields in line 29861, saw 5
Skipping line 45236: Expected 4 fields in line 45236, saw 5
Skipping line 45261: Expected 4 fields in line 45261, saw 5
Skipping line 84285: Expected 4 fields in line 84285, saw 6
Skipping line 84872: Expected 4 fields in line 84872, saw 5
Skipping line 88924: Expected 4 fields in line 88924, saw 6
Skipping line 91464: Expected 4 fields in line 91464, saw 5
Skipping line 107090: Expected 4 fields in line 107090, saw 5
Skipping line 112544: Expected 4 fields in line 112544, saw 5
Skipping line 117812: Expected 4 fields in line 117812, saw 5
Skipping line 130595: Expected 4 fields in line 130595, saw 6
Skipping line 155687: Expected 4 fields in line 155687, saw 5
Skipping line 164079: Expected 4 fields in line 164079, saw 5
Skipping line 164337: Expected 4 fields in line 164337, saw 5
Skipping line 172709: Expected 4 fields in line 172709, saw 5
Skipping line 205738: Expected 4 fields in line 205738, saw 5
Skipping line 280592: Expected 4 fields in line 280592, saw 5
Skipping line 293254: Expected 4 fields in line 293254, saw 5
Skipping line 303973: Expected 4 fields in line 303973, saw 6
Skipping line 308338: Expected 4 fields in line 308338, saw 5
Skipping line 315476: Expected 4 fields in line 315476, saw 5
Skipping line 324469: Expected 4 fields in line 324469, saw 5
Skipping line 327145: Expected 4 fields in line 327145, saw 5
Skipping line 360367: Expected 4 fields in line 360367, saw 5
Skipping line 365616: Expected 4 fields in line 365616, saw 5
Skipping line 386306: Expected 4 fields in line 386306, saw 5
Skipping line 403097: Expected 4 fields in line 403097, saw 18
Skipping line 403098: Expected 4 fields in line 403098, saw 6
Skipping line 404401: Expected 4 fields in line 404401, saw 5
Skipping line 424380: Expected 4 fields in line 424380, saw 5
Skipping line 427951: Expected 4 fields in line 427951, saw 5
Skipping line 440494: Expected 4 fields in line 440494, saw 5
Skipping line 441360: Expected 4 fields in line 441360, saw 5
Skipping line 476903: Expected 4 fields in line 476903, saw 5
Skipping line 527044: Expected 4 fields in line 527044, saw 5
Skipping line 548387: Expected 4 fields in line 548387, saw 5
Skipping line 555455: Expected 4 fields in line 555455, saw 5
Skipping line 559094: Expected 4 fields in line 559094, saw 5
Skipping line 561813: Expected 4 fields in line 561813, saw 5
Skipping line 567084: Expected 4 fields in line 567084, saw 5
Skipping line 580044: Expected 4 fields in line 580044, saw 6
Skipping line 580427: Expected 4 fields in line 580427, saw 5
Skipping line 588229: Expected 4 fields in line 588229, saw 5
Skipping line 588599: Expected 4 fields in line 588599, saw 5
Skipping line 590884: Expected 4 fields in line 590884, saw 5
Skipping line 591095: Expected 4 fields in line 591095, saw 6
Skipping line 594470: Expected 4 fields in line 594470, saw 5
Skipping line 603592: Expected 4 fields in line 603592, saw 5
Skipping line 610085: Expected 4 fields in line 610085, saw 5
Skipping line 135748: field larger than field limit (131072)
Skipping line 4973: Expected 4 fields in line 4973, saw 5
Skipping line 10226: Expected 4 fields in line 10226, saw 5
Skipping line 10885: Expected 4 fields in line 10885, saw 5
Skipping line 12499: Expected 4 fields in line 12499, saw 5
Skipping line 13180: Expected 4 fields in line 13180, saw 5
Skipping line 14196: Expected 4 fields in line 14196, saw 5
Skipping line 24999: Expected 4 fields in line 24999, saw 5
Skipping line 28459: Expected 4 fields in line 28459, saw 5
Skipping line 37778: Expected 4 fields in line 37778, saw 5
Skipping line 59053: Expected 4 fields in line 59053, saw 5
Skipping line 59708: Expected 4 fields in line 59708, saw 5
Skipping line 81910: Expected 4 fields in line 81910, saw 5
Skipping line 95106: Expected 4 fields in line 95106, saw 5
Skipping line 95764: Expected 4 fields in line 95764, saw 5
Skipping line 103517: Expected 4 fields in line 103517, saw 5
Skipping line 147951: Expected 4 fields in line 147951, saw 5
Skipping line 148869: Expected 4 fields in line 148869, saw 5
Skipping line 148973: Expected 4 fields in line 148973, saw 5
Skipping line 154588: Expected 4 fields in line 154588, saw 5
Skipping line 155580: Expected 4 fields in line 155580, saw 5
Skipping line 182725: Expected 4 fields in line 182725, saw 5
Skipping line 190348: Expected 4 fields in line 190348, saw 5
Skipping line 199945: Expected 4 fields in line 199945, saw 5
Skipping line 215645: Expected 4 fields in line 215645, saw 5
Skipping line 220449: Expected 4 fields in line 220449, saw 5
Skipping line 220756: Expected 4 fields in line 220756, saw 5
Skipping line 224226: Expected 4 fields in line 224226, saw 6
Skipping line 251368: Expected 4 fields in line 251368, saw 7
Skipping line 251369: Expected 4 fields in line 251369, saw 5
Skipping line 251370: Expected 4 fields in line 251370, saw 5
Skipping line 264555: Expected 4 fields in line 264555, saw 5
Skipping line 303231: Expected 4 fields in line 303231, saw 5
Skipping line 309826: Expected 4 fields in line 309826, saw 5
Skipping line 309928: Expected 4 fields in line 309928, saw 5
Skipping line 312833: Expected 4 fields in line 312833, saw 6
Skipping line 320161: Expected 4 fields in line 320161, saw 5
Skipping line 322289: Expected 4 fields in line 322289, saw 5
Skipping line 327688: Expected 4 fields in line 327688, saw 5
Skipping line 351158: Expected 4 fields in line 351158, saw 5
Skipping line 374127: Expected 4 fields in line 374127, saw 5
Skipping line 379499: Expected 4 fields in line 379499, saw 5
Skipping line 382724: Expected 4 fields in line 382724, saw 5
Skipping line 410056: Expected 4 fields in line 410056, saw 5
Skipping line 415538: Expected 4 fields in line 415538, saw 6
Skipping line 457051: Expected 4 fields in line 457051, saw 5
Skipping line 460053: Expected 4 fields in line 460053, saw 5
Skipping line 474586: Expected 4 fields in line 474586, saw 5
Skipping line 541206: Expected 4 fields in line 541206, saw 5
Skipping line 543229: Expected 4 fields in line 543229, saw 5
Skipping line 560689: Expected 4 fields in line 560689, saw 5
Skipping line 573132: Expected 4 fields in line 573132, saw 5
Skipping line 577350: Expected 4 fields in line 577350, saw 5
Skipping line 579196: Expected 4 fields in line 579196, saw 5
Skipping line 581342: Expected 4 fields in line 581342, saw 5
Skipping line 600692: Expected 4 fields in line 600692, saw 5
Skipping line 10630: Expected 4 fields in line 10630, saw 5
Skipping line 23487: Expected 4 fields in line 23487, saw 5
Skipping line 30202: Expected 4 fields in line 30202, saw 5
Skipping line 57991: Expected 4 fields in line 57991, saw 5
Skipping line 60502: Expected 4 fields in line 60502, saw 5
Skipping line 65151: Expected 4 fields in line 65151, saw 5
Skipping line 73624: Expected 4 fields in line 73624, saw 5
Skipping line 74416: Expected 4 fields in line 74416, saw 5
Skipping line 90555: Expected 4 fields in line 90555, saw 5
Skipping line 100257: Expected 4 fields in line 100257, saw 5
Skipping line 109018: Expected 4 fields in line 109018, saw 5
Skipping line 121983: Expected 4 fields in line 121983, saw 5
Skipping line 129919: Expected 4 fields in line 129919, saw 5
Skipping line 142117: Expected 4 fields in line 142117, saw 18
Skipping line 142118: Expected 4 fields in line 142118, saw 6
Skipping line 144673: Expected 4 fields in line 144673, saw 5
Skipping line 185305: Expected 4 fields in line 185305, saw 5
Skipping line 241983: Expected 4 fields in line 241983, saw 5
Skipping line 250360: Expected 4 fields in line 250360, saw 11
Skipping line 276262: Expected 4 fields in line 276262, saw 5
Skipping line 289284: Expected 4 fields in line 289284, saw 5
Skipping line 291084: Expected 4 fields in line 291084, saw 6
Skipping line 303271: Expected 4 fields in line 303271, saw 5
Skipping line 315337: Expected 4 fields in line 315337, saw 5
Skipping line 342673: Expected 4 fields in line 342673, saw 7
Skipping line 342674: Expected 4 fields in line 342674, saw 5
Skipping line 342675: Expected 4 fields in line 342675, saw 5
Skipping line 377882: Expected 4 fields in line 377882, saw 5
Skipping line 425500: Expected 4 fields in line 425500, saw 5
Skipping line 428035: Expected 4 fields in line 428035, saw 5
Skipping line 471461: Expected 4 fields in line 471461, saw 5
Skipping line 476656: Expected 4 fields in line 476656, saw 5
Skipping line 505335: Expected 4 fields in line 505335, saw 5
Skipping line 576862: Expected 4 fields in line 576862, saw 5
Skipping line 579597: Expected 4 fields in line 579597, saw 5
Skipping line 606271: Expected 4 fields in line 606271, saw 5
Skipping line 2996: Expected 4 fields in line 2996, saw 5
Skipping line 14406: Expected 4 fields in line 14406, saw 6
Skipping line 55158: Expected 4 fields in line 55158, saw 5
Skipping line 87803: Expected 4 fields in line 87803, saw 5
Skipping line 94597: Expected 4 fields in line 94597, saw 6
Skipping line 113242: Expected 4 fields in line 113242, saw 5
Skipping line 128920: Expected 4 fields in line 128920, saw 5
Skipping line 155745: Expected 4 fields in line 155745, saw 5
Skipping line 165916: Expected 4 fields in line 165916, saw 18
Skipping line 165917: Expected 4 fields in line 165917, saw 6
Skipping line 177235: Expected 4 fields in line 177235, saw 18
Skipping line 177236: Expected 4 fields in line 177236, saw 6
Skipping line 179937: Expected 4 fields in line 179937, saw 5
Skipping line 186013: Expected 4 fields in line 186013, saw 5
Skipping line 189489: Expected 4 fields in line 189489, saw 5
Skipping line 212813: Expected 4 fields in line 212813, saw 5
Skipping line 213841: Expected 4 fields in line 213841, saw 5
Skipping line 237265: Expected 4 fields in line 237265, saw 5
Skipping line 242466: Expected 4 fields in line 242466, saw 5
Skipping line 247559: Expected 4 fields in line 247559, saw 5
Skipping line 299538: Expected 4 fields in line 299538, saw 5
Skipping line 353415: Expected 4 fields in line 353415, saw 5
Skipping line 360407: Expected 4 fields in line 360407, saw 5
Skipping line 362784: Expected 4 fields in line 362784, saw 5
Skipping line 376794: Expected 4 fields in line 376794, saw 5
Skipping line 381324: Expected 4 fields in line 381324, saw 5
Skipping line 396958: Expected 4 fields in line 396958, saw 5
Skipping line 400676: Expected 4 fields in line 400676, saw 5
Skipping line 431954: Expected 4 fields in line 431954, saw 5
Skipping line 437790: Expected 4 fields in line 437790, saw 5
Skipping line 442866: Expected 4 fields in line 442866, saw 11
Skipping line 452454: Expected 4 fields in line 452454, saw 5
Skipping line 460895: Expected 4 fields in line 460895, saw 5
Skipping line 480223: Expected 4 fields in line 480223, saw 5
Skipping line 486028: Expected 4 fields in line 486028, saw 18
Skipping line 486029: Expected 4 fields in line 486029, saw 6
Skipping line 494292: Expected 4 fields in line 494292, saw 5
Skipping line 497513: Expected 4 fields in line 497513, saw 5
Skipping line 531446: Expected 4 fields in line 531446, saw 6
Skipping line 536224: Expected 4 fields in line 536224, saw 5
Skipping line 536361: Expected 4 fields in line 536361, saw 5
Skipping line 540061: Expected 4 fields in line 540061, saw 6
Skipping line 545247: Expected 4 fields in line 545247, saw 11
Skipping line 565700: Expected 4 fields in line 565700, saw 6
Skipping line 566808: Expected 4 fields in line 566808, saw 7
Skipping line 11628: Expected 4 fields in line 11628, saw 5

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [t͡ʃ] << [r], [ɾ] <<..."

## No errors in table_id

In [3]:
df[~df["table_id"].str.startswith("../../../ru-wiki-tables")]

Empty DataFrame
Columns: [table_id, column_id, column_header, column_data]
Index: []

## Filter na columns

In [4]:
df[df["column_data"].isna()]

,table_id,column_id,column_header,column_data
90,../../../ru-wiki-tables-dataset/Dataset/data/8...,0,Позиция,NaN
91,../../../ru-wiki-tables-dataset/Dataset/data/8...,1,Игрок,NaN
92,../../../ru-wiki-tables-dataset/Dataset/data/8...,2,Откуда,NaN
93,../../../ru-wiki-tables-dataset/Dataset/data/8...,3,Сумма,NaN
94,../../../ru-wiki-tables-dataset/Dataset/data/8...,4,Дата,NaN
...,...,...,...,...
7388908,../../../ru-wiki-tables-dataset/Dataset/data/3...,4,Велярные,NaN
7388912,../../../ru-wiki-tables-dataset/Dataset/data/8...,2,Страна,NaN
7389087,../../../ru-wiki-tables-dataset/Dataset/data/2...,2,Тип,NaN
7389108,../../../ru-wiki-tables-dataset/Dataset/data/5...,4,Изображение,NaN
7389224,../../../ru-wiki-tables-dataset/Dataset/data/4...,1,Илл.,NaN

In [5]:
df = df[~df["column_data"].isna()]
df

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [t͡ʃ] << [r], [ɾ] <<..."

In [6]:
df = df[df["column_data"].str.strip() != ""]
df

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [t͡ʃ] << [r], [ɾ] <<..."

## Remove `Unnamed: .`

In [7]:
df.loc[:, "column_data"] = df["column_data"].progress_apply(
    lambda x: re.sub(r"Unnamed:\s\d+_level_\d+", " ", x)
)
df["column_data"].str.contains("Unnamed").sum()

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7042163/7042163 [00:06<00:00, 1127037.10it/s]

50

In [8]:
unnamed_mask = df["column_data"].str.contains("Unnamed")
df[unnamed_mask][:10]

,table_id,column_id,column_header,column_data
107162,../../../ru-wiki-tables-dataset/Dataset/data/2...,2,Название[К 1],Адэр (полуостров) (англ.)русск.[8] (англ. Adar...
229090,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,Title,«The Motivation Proclamation» << «Waiting» << ...
469078,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,Название,Сан-Хуан[14] (исп. San Juan) << Валье-Нуэво[15...
782127,../../../ru-wiki-tables-dataset/Dataset/data/5...,2,Role,Jake Kincaid << Steven Hines << Skip << Brian ...
842052,../../../ru-wiki-tables-dataset/Dataset/data/8...,3,3,Амелия 1978 << Клодетт 1979 << Имельда 2019 <<...
873605,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,Название,Сан-Хуан[14] (исп. San Juan) << Валье-Нуэво[15...
925958,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,Название[К 1],Аниакчак[46] (англ. Aniakchak) << Блэк-Пик[47]...
1152304,../../../ru-wiki-tables-dataset/Dataset/data/8...,4,Примечания,Эпизод: «Unnamed» << Эпизод: «When Sunny Gets ...
1501832,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,Название,«News Cycle» << «Off the Record» << «The Essen...
1607206,../../../ru-wiki-tables-dataset/Dataset/data/6...,2,Название,Аву[140] (индон. Awu) << Бануа-Уху[141] (индон...

## Remove: `.mw-parser`

In [9]:
df.loc[:, "column_data"] = df["column_data"].progress_apply(
    lambda x: re.sub(r"@media.+{.+}", " ", x)
)
df["column_data"].str.contains("mw-parser").sum()

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7042163/7042163 [00:06<00:00, 1116665.49it/s]

24301

In [10]:
# r"\.mw-parser-output \..+{.+}"
# r"\.mw-parser-output \.ts.+{.+}"

df.loc[:, "column_data"] = df["column_data"].progress_apply(
    lambda x: re.sub(r"\.mw-parser-output .+{.+}", " ", x)
)
df["column_data"].str.contains("mw-parser").sum()

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7042163/7042163 [00:06<00:00, 1100108.45it/s]

0

In [11]:
df[df["column_data"].str.contains("mw-parser")]

Empty DataFrame
Columns: [table_id, column_id, column_header, column_data]
Index: []

## Remove Wikipedia links

In [12]:
df.loc[:, "column_data"] = df["column_data"].progress_apply(lambda x: re.sub(r"\[[0-9]*\]", "", x))
df

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7042163/7042163 [00:07<00:00, 1000609.79it/s]

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [t͡ʃ] << [r], [ɾ] <<..."

## Remove bad symbols

In [13]:
"−" == "—"

False

In [14]:
def remove_non_alphabetic_symbols(col_name: str) -> str:
    """TODO: just replace this symbols with space"""
    non_restricted_symbols = [
        "(",
        ")",
        "+",
        "-",
        "−",
        "[",
        "]",
        "/",
        ".",
        ",",
        "@",
        "{",
        "}",
        "«",
        "»",
        "<",
        ">",
        ":",
        ";",
        "'",
        "*",
        "?",
        "—",
        "!",
        "_",
    ]
    return "".join(c for c in col_name if c.isalpha() or c.isdigit() or c.isspace() or c in non_restricted_symbols)

df.loc[:, "column_data"] = df["column_data"].progress_apply(lambda x: remove_non_alphabetic_symbols(str(x)))
df

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7042163/7042163 [02:24<00:00, 48802.51it/s]

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [tʃ] << [r], [ɾ] << ..."

## Remove empty column_data

In [15]:
one_sep_mask = df["column_data"] == " << "
df[one_sep_mask]

,table_id,column_id,column_header,column_data
837,../../../ru-wiki-tables-dataset/Dataset/data/8...,4,Ист.,<<
1308,../../../ru-wiki-tables-dataset/Dataset/data/3...,7,Пр.,<<
2664,../../../ru-wiki-tables-dataset/Dataset/data/9...,2,Численность.1,<<
3192,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,Численность.1,<<
3422,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,Ист.,<<
...,...,...,...,...
7386596,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,5,<<
7386597,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,6,<<
7386598,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,7,<<
7386599,../../../ru-wiki-tables-dataset/Dataset/data/2...,8,8,<<
7388049,../../../ru-wiki-tables-dataset/Dataset/data/8...,6,Ссылки,<<

In [16]:
df = df[~one_sep_mask]
df

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [tʃ] << [r], [ɾ] << ..."

In [17]:
mul_sep_mask = df["column_data"].progress_apply(lambda x: "".join(x.split("<<")).isspace())
df[mul_sep_mask]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7037468/7037468 [00:09<00:00, 730733.10it/s]

,table_id,column_id,column_header,column_data
19,../../../ru-wiki-tables-dataset/Dataset/data/4...,5,.mw-parser-output .ts-comment-commentedText{bo...,<< << << << << << << << << << << <...
353,../../../ru-wiki-tables-dataset/Dataset/data/6...,5,Ссылка,<< << << << << << <<
399,../../../ru-wiki-tables-dataset/Dataset/data/1...,2,Численность.1,<< << << << << << << << << <<
402,../../../ru-wiki-tables-dataset/Dataset/data/1...,2,Численность.1,<< << << << << << <<
548,../../../ru-wiki-tables-dataset/Dataset/data/1...,2,Численность.1,<< << << <<
...,...,...,...,...
7388359,../../../ru-wiki-tables-dataset/Dataset/data/5...,2,Численность.1,<< << << <<
7388538,../../../ru-wiki-tables-dataset/Dataset/data/1...,0,0,
7388752,../../../ru-wiki-tables-dataset/Dataset/data/4...,4,"Сёла, исчезнувшие после 1948 года",
7388988,../../../ru-wiki-tables-dataset/Dataset/data/5...,2,Численность.1,<< << << <<
7389084,../../../ru-wiki-tables-dataset/Dataset/data/1...,2,Численность.1,<< << << <<

In [18]:
df = df[~mul_sep_mask]
df

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [tʃ] << [r], [ɾ] << ..."

In [19]:
empty_mask = df["column_data"] == ""
df[empty_mask]

,table_id,column_id,column_header,column_data
100,../../../ru-wiki-tables-dataset/Dataset/data/8...,4,Ссылка,
894,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,№,
2599,../../../ru-wiki-tables-dataset/Dataset/data/4...,0,Матчи Аит-Фана за сборную Марокко,
3273,../../../ru-wiki-tables-dataset/Dataset/data/6...,4,Прим.,
8107,../../../ru-wiki-tables-dataset/Dataset/data/8...,2,Перепись 2011,
...,...,...,...,...
7385274,../../../ru-wiki-tables-dataset/Dataset/data/4...,4,4,
7385320,../../../ru-wiki-tables-dataset/Dataset/data/5...,3,Ссылки,
7386370,../../../ru-wiki-tables-dataset/Dataset/data/2...,0,Матчи и голы Бибраса Натхо за сборную Израиля,
7386417,../../../ru-wiki-tables-dataset/Dataset/data/5...,4,Сноски,
7388797,../../../ru-wiki-tables-dataset/Dataset/data/8...,5,Ссылка,

In [20]:
df = df[~empty_mask]
df

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [tʃ] << [r], [ɾ] << ..."

## Remove empty cells

In [21]:
def remove_empty_cells(x: str) -> str:
    li = x.split(" << ")
    res = [i for i in li if not i.isspace() and i != ""]
    return " << ".join(res)

df.loc[:, "column_data"] = df["column_data"].progress_apply(remove_empty_cells)
df

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6887005/6887005 [00:13<00:00, 509618.77it/s]

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [tʃ] << [r], [ɾ] << ..."

## Remove columns that have len < 3 rows

In [22]:
ge_3_rows_mask = df["column_data"].str.count("<<") >= 2
df[~ge_3_rows_mask]

,table_id,column_id,column_header,column_data
34,../../../ru-wiki-tables-dataset/Dataset/data/9...,0,Число,Китайский вариант << Японский вариант
35,../../../ru-wiki-tables-dataset/Dataset/data/9...,1,1,一 (ити) << 一つ (хитоцу)
36,../../../ru-wiki-tables-dataset/Dataset/data/9...,2,2,二 (ни) << 二つ (футацу)
37,../../../ru-wiki-tables-dataset/Dataset/data/9...,3,3,三 (сан) << 三つ (мицу)
38,../../../ru-wiki-tables-dataset/Dataset/data/9...,4,4,四 (си) << 四つ (ёцу)
...,...,...,...,...
7389208,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,Подиумы.1,0
7389209,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,Очки,3
7389210,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,Очки.1,3
7389211,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,БК,0
7389212,../../../ru-wiki-tables-dataset/Dataset/data/7...,5,БК.1,0

In [23]:
df = df[ge_3_rows_mask]
df

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [tʃ] << [r], [ɾ] << ..."

In [24]:
def has_ge3_unique_cells(x: str) -> bool:
    li = x.split(" << ")
    unique_values = set(li)
    if len(set(li)) < 3:
        return False
    return True

has_ge3_unique_cells_mask = df["column_data"].progress_apply(has_ge3_unique_cells)
df[~has_ge3_unique_cells_mask]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5096684/5096684 [00:13<00:00, 368981.98it/s]

,table_id,column_id,column_header,column_data
27,../../../ru-wiki-tables-dataset/Dataset/data/6...,4,Примечания,- << - << - << - << - << - << - << - << - << -...
64,../../../ru-wiki-tables-dataset/Dataset/data/1...,1,2014—2015,6 << 6 << 2
116,../../../ru-wiki-tables-dataset/Dataset/data/8...,2,И,52 << 52 << 52 << 52 << 52 << 52 << 52 << 52 <...
126,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,3 << 0 << 0
127,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,4 << 0 << 0
...,...,...,...,...
7389215,../../../ru-wiki-tables-dataset/Dataset/data/5...,2,И,36 << 36 << 36 << 36 << 36 << 36 << 36 << 36
7389223,../../../ru-wiki-tables-dataset/Dataset/data/4...,0,Год,1880.0 << 1881.0 << 1881.0 << 1881.0 << 1881.0...
7389245,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,Игры,3 << 3 << 3 << 3
7389247,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,Ничьи,0 << 0 << 0 << 0
7389258,../../../ru-wiki-tables-dataset/Dataset/data/2...,7,Отчёт,0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0 << 0...

In [25]:
df = df[has_ge3_unique_cells_mask]
df

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389255,../../../ru-wiki-tables-dataset/Dataset/data/2...,4,Голы «Торпедо»,"? << ? << ? << игроки на просмотре (1, 1— с пе..."
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [tʃ] << [r], [ɾ] << ..."

## Save preprocessed dataset

In [26]:
import numpy as np

number_of_chunks = 12
for id, chunk in tqdm(enumerate(np.array_split(df, number_of_chunks))):
    chunk.to_csv(f"./preprocessed/data_{id}.csv", sep="|", index=False)

df

/home/kirilltobola/Dev/github.com/RuTaBERT-Dataset/venv/lib/python3.12/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
12it [00:25,  2.15s/it]

,table_id,column_id,column_header,column_data
0,../../../ru-wiki-tables-dataset/Dataset/data/7...,0,0,Конференция Кларенса Кэмпбелла << Дивизион Нор...
1,../../../ru-wiki-tables-dataset/Dataset/data/7...,1,1,Конференция Кларенса Кэмпбелла << Дивизион Нор...
2,../../../ru-wiki-tables-dataset/Dataset/data/7...,2,2,Конференция Кларенса Кэмпбелла << Дивизион Нор...
3,../../../ru-wiki-tables-dataset/Dataset/data/7...,3,3,Конференция Кларенса Кэмпбелла << Дивизион Нор...
4,../../../ru-wiki-tables-dataset/Dataset/data/7...,4,4,Конференция Кларенса Кэмпбелла << Дивизион Нор...
...,...,...,...,...
7389255,../../../ru-wiki-tables-dataset/Dataset/data/2...,4,Голы «Торпедо»,"? << ? << ? << игроки на просмотре (1, 1— с пе..."
7389256,../../../ru-wiki-tables-dataset/Dataset/data/2...,5,Арбитр,? << Алексей Еськов << ? << Алексей Еськов << ...
7389257,../../../ru-wiki-tables-dataset/Dataset/data/2...,6,Зрители,100.0 << 200.0 << 50.0 << 300.0 << 500.0
7389259,../../../ru-wiki-tables-dataset/Dataset/data/6...,0,Буква,N n << O o << P p << Q q << R r << S s << T t ...
7389260,../../../ru-wiki-tables-dataset/Dataset/data/6...,1,МФА,"[n] << [o], [ɔ] << [p] << [tʃ] << [r], [ɾ] << ..."